//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homestaylist
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomestayEntities : DbContext
    {
        public HomestayEntities()
            : base("name=HomestayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Homestayown> Homestayown { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
